language: perl


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y r-base-core cpanminus unzip # gcc git
  - sudo cpanm Statistics::R
  - sudo cpanm JSON
  - sudo Rscript -e "install.packages('ape', dependencies = T, repos='http://cran.rstudio.com/')"
  - sudo ./build_3rd_party.sh

