language: perl

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - cpanminus
      - r-base-dev  
      - r-recommended
      - pandoc

cache:
  directories:
    - ~/Rlib
      
before_install:
  - cpanm -nf Statistics::R || cat /home/travis/.cpanm/work/*/build.log
  - cpanm -n JSON
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e 'if(!"ape" %in% rownames(installed.packages())) { install.packages("ape", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - ./build_3rd_party.sh ~
