
language: perl

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - cpanminus
      - r-base-dev  
cache:
  directories:
    - ~/travis_R_lib
      
before_install:
  - echo 'R_LIBS=~/travis_R_lib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e '{ install.packages("ape", dependencies = TRUE, lib = "~/travis_R_lib")}'
  - cpanm -nf Statistics::R || cat /home/travis/.cpanm/work/*/build.log
  - cpanm -n JSON
  - ./build_3rd_party.sh ~