language: perl

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - cpanminus
      - r-base

      
before_install:
  - cpanm -nf Statistics::R || cat /home/travis/.cpanm/work/*/build.log
  - cpanm -n JSON
  - Rscript -e "install.packages('ape', dependencies = T, repos='http://cran.rstudio.com/')"
  - ./build_3rd_party.sh ~
