package:
  name: seq-gen
  version: 1.3.3

source:
  fn: Seq-Gen.v1.3.3.tgz
  url: http://tree.bio.ed.ac.uk/download.php?id=85
  md5: ca77c79b93d9e41c2f3f38ac6d218977

test:
  commands:
    - seq-gen -h

about:
  home: http://tree.bio.ed.ac.uk/software/seqgen/
  summary: An application for the Monte Carlo simulation of molecular sequence evolution along phylogenetic trees.
