package:
  name: perl-ipc-run
  version: 0.96

source:
  fn: IPC-Run-0.96.tar.gz
  url: http://search.cpan.org/CPAN/authors/id/T/TO/TODDR/IPC-Run-0.96.tar.gz

requirements:
  build:
    - gcc
    - perl 5.22.2.1
  run:
    - libgcc
    - perl 5.22.2.1

test:
  imports:
    - IPC-Run

about:
  home: http://search.cpan.org/~toddr/IPC-Run-0.96/lib/IPC/Run.pm
  summary: system() and background procs w/ piping redirs ptys